<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>c2cd6cd8-f6e1-4d40-b3ee-b5983efac3e8</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.8" />
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AI.Features\AI.Features.csproj" />
    <ProjectReference Include="..\AI.Shared\AI.Shared.csproj" />
    <ProjectReference Include="..\AI.Infrastructure\AI.Infrastructure.csproj" />
  </ItemGroup>

</Project>
